# Path to icons for different themes
DARK_ICON_PATH=themeIcons/dark_theme.png
LIGHT_ICON_PATH=themeIcons/light_theme.png

# Custom colors for a dark theme
Component.focusColor = #9966FF
Button.hoverBackground = #3C3F41
MenuItem.selectionBackground = #555555
Table.selectionBackground = #4B6EAF
List.selectionBackground = #555555

